---
- hosts: all
  become: yes
  tasks:
    - name: Update APT and cache and Install Nginx
      apt: 
       name: nginx 
       state: latest
    - name: start nginx
      service:
          name: nginx
          state: started