---
- hosts: frontend
  become: true
  vars_files:
    - vars/vars.yml

  tasks:
    - name: Install prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
      tags: [ system ]

 
  # UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
      tags: [ system ]



  # WordPress Configuration
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/wordpress"
        remote_src: yes
        creates: "/var/www/wordpress"
      tags: [ wordpress ]

    - name: Set ownership
      file:
        path: "/var/www/wordpress"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      tags: [ wordpress ]
    
    #- name: Set the correct permissions on Wordpress directories
     # command: find /var/www/html/wordpress/ -type d -exec chmod 755 {} \;

    - name: Set the correct permissions on Wordpress directories
      command: find /var/www/wordpress/ -type d -exec chmod 755 {} \;

    #- name: Set permissions for directories
    #  shell: "/usr/bin/find /var/www/html/wordpress/ -type d -exec chmod 750 {} \\;"
    #  tags: [ wordpress ]

    #- name: Set permissions for files
    #  shell: "/usr/bin/find /var/www/html/wordpress/ -type f -exec chmod 640 {} \\;"
    #  tags: [ wordpress ]

    - name: Set up wp-config
      template:
        src: "files/vhost.conf.j2"
        dest: "/var/www/wordpress/wp-config.php"
      tags: [ wordpress ]
    
    - name: Restart Nginx Service
      command: nginx -s reload

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted